apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube1-deployment
  labels:
    app: my-kube-app1
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: my-kube-app1
  template:
    metadata:
      labels:
        app: my-kube-app1
    spec:
      containers:
        - name: my-kube1-container
          image: shiv4j/my-kube1:latest  # Your Docker image
          ports:
            - containerPort: 3001  # Port inside the container
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "production"